import{createClient}from'@supabase/supabase-js'

const supabaseUrl=import.meta.env.VITE_SUPABASE_URL||'https://xtqwbyfolbmiidiurmch.supabase.co'
const supabaseAnonKey=import.meta.env.VITE_SUPABASE_ANON_KEY||'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0cXdieWZvbGJtaWlkaXVybWNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODEyODg0MDAsImV4cCI6MjA5Njg2NDQwMH0.8b1-QAQrqIxLy97rBDJkDwTm2sMP0-QoiQJ2T-Iv0bo'

export const supabase=createClient(supabaseUrl,supabaseAnonKey)
